version: "3.9" # docker sintaxe version

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app # modificações na maquina local, refletem em tempo real no container
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
